name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    name: Test the action
    steps:
      - uses: actions/checkout@v2
        
      - name: Get code coverage
        uses: ./ # Uses an action in the root directory
        id: test_step
        with:
          opencover_path: "test/coverage.opencover.xml"
        
      - name: Print code coverage
        run: echo "Code coverage percentage ${{ steps.test_step.outputs.coverage_percentage }} %"
